apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webmethods-apigateway.fullname" . }}
  labels:
    {{- include "webmethods-apigateway.labels" . | nindent 4 }}
data:
  config-sources.yml: |-
    sources:
      {{- if .Values.fullConfigs }}
      - type: YAML
        allowEdit: false
        properties:
          location: full.yml
      {{- else }}
      {{- if .Values.connectElasticSearch.enabled }}
      - type: YAML
        allowEdit: false
        properties:
          location: elasticsearch.yml
      {{- end }}
      {{- if .Values.connectAnalyticsDataStore.enabled }}
      - type: YAML
        allowEdit: false
        properties:
          location: analyticsDataStore.yml
      {{- end }}
      {{- if .Values.connectKibana.enabled }}
      - type: YAML
        allowEdit: false
        properties:
          location: kibana.yml
      {{- end }}
      {{- if include "webmethods-apigateway.isClusteringIgnite" (default "none" ((.Values.clustering).type)) }}
      - type: YAML
        allowEdit: false
        properties:
          location: clustering_ignite.yml
      {{- else }}
      {{- if include "webmethods-apigateway.isClusteringTerracotta" (default "none" ((.Values.clustering).type)) }}
      - type: YAML
        allowEdit: false
        properties:
          location: clustering_terracotta.yml
      {{- end }}
      {{- end }}
      {{- if .Values.extraConfigs }}
      - type: YAML
        allowEdit: false
        properties:
          location: extras.yml
      {{- end }}
      {{- end }}

  {{- if .Values.fullConfigs }}
  full.yml:
    {{- toYaml .Values.fullConfigs | nindent 4 }}
  
  {{- else }}

  {{- if .Values.extraConfigs }}
  extras.yml:
    {{- toYaml .Values.extraConfigs | nindent 4 }}
  {{- end }}
  
  {{- if .Values.connectElasticSearch.enabled }}
  elasticsearch.yml:
    {{- toYaml .Values.connectElasticSearch.configs | nindent 4 }}
  {{- end }}

  {{- if .Values.connectAnalyticsDataStore.enabled }}
  analyticsDataStore.yml:
    {{- toYaml .Values.connectAnalyticsDataStore.configs | nindent 4 }}
  {{- end }}

  {{- if .Values.connectKibana.enabled }}
  kibana.yml:
    {{- toYaml .Values.connectKibana.configs | nindent 4 }}
  {{- end }}

  {{- if include "webmethods-apigateway.isClusteringIgnite" (default "none" ((.Values.clustering).type))  }}
  clustering_ignite.yml: |-
    apigw:
      cluster:
        aware: true
        name: {{ default "APIGatewayCluster" ((.Values.clustering).name) }}
        sessTimeout: {{ default "60" ((.Values.clustering).sessionTimeout) }}
        actionOnStartupError: {{ default "shutdown" ((.Values.clustering).actionOnStartupError) }}
        ignite:
          discoveryPort: {{ default "47100" (((.Values.clustering).ignite).discoveryPort) }}
          communicationPort: {{ default "47500" (((.Values.clustering).ignite).communicationPort) }}
          portRange: {{ default "0" (((.Values.clustering).ignite).portRange) }}
          k8sServiceName: {{ include "webmethods-apigateway.gwruntimeFullname" . }}
          k8sNamespace: {{ .Release.Namespace }}
  {{- else }}
  {{- if include "webmethods-apigateway.isClusteringTerracotta" (default "none" ((.Values.clustering).type)) }}
  clustering_terracotta.yml: |-
    apigw:
      cluster:
        aware: true
        name: {{ default "APIGatewayCluster" ((.Values.clustering).name) }}
        sessTimeout: {{ default "60" ((.Values.clustering).sessionTimeout) }}
        actionOnStartupError: {{ default "shutdown" ((.Values.clustering).actionOnStartupError) }}
        tsaUrls: {{ ((.Values.clustering).terracotta).url }}
  {{- end }}
  {{- end }}
  
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webmethods-apigateway.fullname" . }}-customscripts
  labels:
    {{- include "webmethods-apigateway.labels" . | nindent 4 }}
data:
{{ tpl ((.Files.Glob "custom/*").AsConfig) . | indent 2 }}
