---
{{- if .Values.ingress.gwruntime.enabled -}}
{{- $uname := (include "webmethods-apigateway.gwruntimeFullname" .) }}
{{- $port := .Values.service.gwruntime.port }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $uname }}
  labels:
    {{- include "webmethods-apigateway.labels" . | nindent 4 }}
  {{- with .Values.ingress.gwruntime.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.gwruntime.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.gwruntime.className }}
  {{- end }}
  {{- if .Values.ingress.gwruntime.tls }}
  tls:
    {{- range .Values.ingress.gwruntime.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.gwruntime.host | quote }}
      http:
        paths:
          {{- range .Values.ingress.gwruntime.paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | quote }}
            backend:
              service:
                name: {{ $uname }}
                port:
                  number: {{ $port }}
          {{- end }}
{{- end }}
---
{{- if .Values.ingress.gwui.enabled -}}
{{- $uname := (include "webmethods-apigateway.gwuiFullname" .) }}
{{- $port := .Values.service.gwui.port }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $uname }}
  labels:
    {{- include "webmethods-apigateway.labels" . | nindent 4 }}
  {{- with .Values.ingress.gwui.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.gwui.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.gwui.className }}
  {{- end }}
  {{- if .Values.ingress.gwui.tls }}
  tls:
    {{- range .Values.ingress.gwui.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.gwui.host | quote }}
      http:
        paths:
          {{- range .Values.ingress.gwui.paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | quote }}
            backend:
              service:
                name: {{ $uname }}
                port:
                  number: {{ $port }}
          {{- end }}
{{- end }}
---
{{- if .Values.ingress.isruntime.enabled -}}
{{- $uname := (include "webmethods-apigateway.isruntimeFullname" .) }}
{{- $port := .Values.service.isruntime.port }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $uname }}
  labels:
    {{- include "webmethods-apigateway.labels" . | nindent 4 }}
  {{- with .Values.ingress.isruntime.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.isruntime.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.isruntime.className }}
  {{- end }}
  {{- if .Values.ingress.isruntime.tls }}
  tls:
    {{- range .Values.ingress.isruntime.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.isruntime.host | quote }}
      http:
        paths:
          {{- range .Values.ingress.isruntime.paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | quote }}
            backend:
              service:
                name: {{ $uname }}
                port:
                  number: {{ $port }}
          {{- end }}
{{- end }}
---
{{- if .Values.ingress.custom.enabled -}}
{{- $uname := (include "webmethods-apigateway.fullname" .) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $uname }}
  labels:
    {{- include "webmethods-devportal.labels" . | nindent 4 }}
  {{- with .Values.ingress.custom.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.custom.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.custom.className }}
  {{- end }}
  {{- if .Values.ingress.custom.tls }}
  tls:
    {{- range .Values.ingress.custom.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.custom.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | quote }}
            backend:
              service:
                name: {{ .backendServiceName }}
                port:
                  number: {{ .backendServicePort }}
          {{- end }}
    {{- end }}
{{- end -}}