---
{{- if .Values.ingress.gwruntime -}}
{{- if .Values.ingress.gwruntime.enabled -}}
{{- $backendUname := (include "webmethods-apigateway.gwruntimeFullname" .) }}
{{- $backendPort := .Values.service.gwruntime.port }}
kind: Ingress
metadata:
  name: {{ include "webmethods-apigateway.gwruntimeFullname" . }}
  labels:
    {{- include "webmethods-apigateway.labels" . | nindent 4 }}
  {{- with .Values.ingress.gwruntime.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.gwruntime.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.gwruntime.className }}
  {{- end }}
  {{- if .Values.ingress.gwruntime.tls }}
  tls:
    {{- range .Values.ingress.gwruntime.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.gwruntime.host | quote }}
      http:
        paths:
          {{- range .Values.ingress.gwruntime.paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | quote }}
            backend:
              service:
                name: {{ $backendUname }}
                port:
                  number: {{ $backendPort }}
          {{- end }}
{{- end }}
{{- end }}
---
{{- if .Values.ingress.custom -}}
{{- if .Values.ingress.custom.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "webmethods-apigateway.fullname" . }}
  labels:
    {{- include "webmethods-devportal.labels" . | nindent 4 }}
  {{- with .Values.ingress.custom.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.custom.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.custom.className }}
  {{- end }}
  {{- if .Values.ingress.custom.tls }}
  tls:
    {{- range .Values.ingress.custom.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.custom.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | quote }}
            backend:
              service:
                name: {{ .backendServiceName }}
                port:
                  number: {{ .backendServicePort }}
          {{- end }}
    {{- end }}
{{- end -}}
{{- end }}