---
{{- if include "webmethods-apigateway.isClusteringIgnite" (default "none" ((.Values.clustering).type)) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: peer2peer-cluster-discovery-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - endpoints
    verbs:
      - get
      - list
      - watch
{{- end }}