---
{{- if .Values.service.gwruntime }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webmethods-apigateway.gwruntimeFullname" . }}
  labels:
    {{- include "webmethods-apigateway.labels" . | nindent 4 }}
  {{- with .Values.service.gwruntime.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.gwruntime.type }}
  ports:
    - port: {{ .Values.service.gwruntime.port }}
      {{- if .Values.service.gwruntime.targetPort }}
      targetPort: {{ .Values.service.gwruntime.targetPort }}
      {{- end }}
      protocol: TCP
      name: gwruntime
  selector:
    {{- include "webmethods-apigateway.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.service.gwruntimessl }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webmethods-apigateway.gwruntimeFullname" . }}-ssl
  labels:
    {{- include "webmethods-apigateway.labels" . | nindent 4 }}
  {{- with .Values.service.gwruntimessl.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.gwruntimessl.type }}
  ports:
    - port: {{ .Values.service.gwruntimessl.port }}
      {{- if .Values.service.gwruntimessl.targetPort }}
      targetPort: {{ .Values.service.gwruntimessl.targetPort }}
      {{- end }}
      protocol: TCP
      name: gwruntimessl
  selector:
    {{- include "webmethods-apigateway.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.service.gwui }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webmethods-apigateway.gwuiFullname" . }}
  labels:
    {{- include "webmethods-apigateway.labels" . | nindent 4 }}
  {{- with .Values.service.gwui.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.gwui.type }}
  ports:
    - port: {{ .Values.service.gwui.port }}
      {{- if .Values.service.gwui.targetPort }}
      targetPort: {{ .Values.service.gwui.targetPort }}
      {{- end }}
      protocol: TCP
      name: gwui
  selector:
    {{- include "webmethods-apigateway.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.service.gwuissl }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webmethods-apigateway.gwuiFullname" . }}-ssl
  labels:
    {{- include "webmethods-apigateway.labels" . | nindent 4 }}
  {{- with .Values.service.gwuissl.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.gwuissl.type }}
  ports:
    - port: {{ .Values.service.gwuissl.port }}
      {{- if .Values.service.gwuissl.targetPort }}
      targetPort: {{ .Values.service.gwuissl.targetPort }}
      {{- end }}
      protocol: TCP
      name: gwuissl
  selector:
    {{- include "webmethods-apigateway.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.service.isruntime }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webmethods-apigateway.isruntimeFullname" . }}
  labels:
    {{- include "webmethods-apigateway.labels" . | nindent 4 }}
  {{- with .Values.service.isruntime.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.isruntime.type }}
  ports:
    - port: {{ .Values.service.isruntime.port }}
      {{- if .Values.service.isruntime.targetPort }}
      targetPort: {{ .Values.service.isruntime.targetPort }}
      {{- end }}
      protocol: TCP
      name: isruntime
  selector:
    {{- include "webmethods-apigateway.selectorLabels" . | nindent 4 }}
{{- end }}