---
{{- if .Values.service.gwruntime }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webmethods-apigateway.gwruntimeFullname" . }}
  labels:
    {{- include "webmethods-apigateway.labels" . | nindent 4 }}
  {{- with .Values.service.gwruntime.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.gwruntime.type }}
  ports:
    - port: {{ .Values.service.gwruntime.port }}
      {{- if .Values.service.gwruntime.targetPort }}
      targetPort: {{ .Values.service.gwruntime.targetPort }}
      {{- end }}
      protocol: TCP
      name: gwruntime
    {{- if .Values.service.gwruntime.portSsl }}
    - port: {{ .Values.service.gwruntime.portSsl }}
      {{- if .Values.service.gwruntime.targetPortSsl }}
      targetPort: {{ .Values.service.gwruntime.targetPortSsl }}
      {{- end }}
      protocol: TCP
      name: gwruntimessl
    {{- end }}
  selector:
    {{- include "webmethods-apigateway.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.service.gwui }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webmethods-apigateway.gwuiFullname" . }}
  labels:
    {{- include "webmethods-apigateway.labels" . | nindent 4 }}
  {{- with .Values.service.gwui.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.gwui.type }}
  ports:
    - port: {{ .Values.service.gwui.port }}
      {{- if .Values.service.gwui.targetPort }}
      targetPort: {{ .Values.service.gwui.targetPort }}
      {{- end }}
      protocol: TCP
      name: gwui
    {{- if .Values.service.gwui.portSsl }}
    - port: {{ .Values.service.gwui.portSsl }}
      {{- if .Values.service.gwui.targetPortSsl }}
      targetPort: {{ .Values.service.gwui.targetPortSsl }}
      {{- end }}
      protocol: TCP
      name: gwuissl
    {{- end }}
  selector:
    {{- include "webmethods-apigateway.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.service.isruntime }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webmethods-apigateway.isruntimeFullname" . }}
  labels:
    {{- include "webmethods-apigateway.labels" . | nindent 4 }}
  {{- with .Values.service.isruntime.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.isruntime.type }}
  ports:
    - port: {{ .Values.service.isruntime.port }}
      {{- if .Values.service.isruntime.targetPort }}
      targetPort: {{ .Values.service.isruntime.targetPort }}
      {{- end }}
      protocol: TCP
      name: isruntime
    {{- if .Values.service.isruntime.portSsl }}
    - port: {{ .Values.service.isruntime.portSsl }}
      {{- if .Values.service.isruntime.targetPortSsl }}
      targetPort: {{ .Values.service.isruntime.targetPortSsl }}
      {{- end }}
      protocol: TCP
      name: isruntimessl
    {{- end }}
  selector:
    {{- include "webmethods-apigateway.selectorLabels" . | nindent 4 }}
{{- end }}
...