# Default values for webmethods-microservicesruntime.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# extra flag to enable/disable the deployment
enabled: true

replicaCount: 1

## SAGGS image
image:
  registry: ghcr.io/sag-gov-integration-unit
  repository: webmethods-microservicesruntime
  pullPolicy: IfNotPresent
  tag: 10.15

## image pull secrets
imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

# the licensing needed for the product
licenseSecret: {}
  # name: ""
  # key: ""

# extra license needed if connecting to terracotta
licenseTerracottaSecret: {}
  # name: ""
  # key: ""

# size of the temp dir for the MSR derbydb
derbyDBSize: 1Gi

# dictionnaries for env variables passed as helm params (or you can use standard "env" list as well)
envConfigs: {}
envSecretConfigs: {}

# config files as config maps
configs:
  fileAccessControl:
    enabled: false
    allowedWritePaths: ""
    allowedReadPaths: ""
    allowedDeletePaths: ""
  metering:
    enabled: false
    serverUrl: http://CHANGEME:8083/metering/api/measurements
    accumulationPeriod: 10
    reportPeriod: 30

persistence:
  logs:
    enabled: false
    size: 5Gi
    storageClassName: "gp2"
    accessMode: "ReadWriteOnce"
  metering:
    enabled: false
    size: 1Gi
    storageClassName: "gp2"
    accessMode: "ReadWriteOnce"
  customdata:
    enabled: false
    size: 10Gi
    storageClassName: "gp2"
    accessMode: "ReadWriteOnce"
    mountPath: "/data"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

## ports exposed by the container
containerPorts:
  runtime: 5555
  diag: 9999

## port exposed by the service
service:
  type: ClusterIP
  port: 5555
  annotations: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

## to add extra volumes and mounts as needed
extraVolumeMounts: ""
extraVolumes: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
