---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webmethods-devportal.fullname" . }}-customscripts
  labels:
    {{- include "webmethods-devportal.labels" . | nindent 4 }}
data:
{{ tpl ((.Files.Glob "custom/*").AsConfig) . | indent 2 }}
