---

# general flags
enabled: true
debug: false

fullnameOverride: ""
nameOverride: ""

# default docker hub image at https://hub.docker.com/r/saggs/webmethods-dbconfigurator
image:
  registry: ghcr.io/sag-gov-integration-unit
  repository: webmethods-dbconfig
  pullPolicy: IfNotPresent
  tag: "10.15"

## Optionally specify an array of imagePullSecrets.
## Secrets must be manually created in the namespace.
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
##
imagePullSecrets: []
# - myRegistryKeySecretName

# possible list of init containers
initContainers: []

externaldb:
  # url: <full jdbc url>
  type: postgres
  host: mft-postgres
  port: 5432
  # args: <args to be added to the jdbc conn string>
  dbName: mftdb
  user: mftdbuser
  passwordSecret: {}
    # name:
    # key:
  
createDb:
  enabled: false
  dbAdminUser: postgres
  dbAdminPasswordSecret: {}
    # name:
    # key:

createObjects:
  enabled: false
  productNames: ""
  componentNames: ""
  productVersion: ""

# Count of re(!)tries. A value of 2 means 3 tries in total.
backoffLimit: 1

# annotations of the Job. Define helm post hook here
annotations:
  "helm.sh/hook": "post-install,post-upgrade,post-rollback"
  "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
  "helm.sh/hook-weight": "5"

labels: {}

## env variable (non secret)
env: {}
  # myenv1: value1
  # myenv2: value2

# Add volumes, e.g. for custom secrets
volumes: ""

# Add volumes mounts, e. g. for custom secrets
volumeMounts: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

## Additional pod labels
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

## Extra Annotations to be added to pod
podAnnotations: {}

# Add volumes, e.g. for custom secrets
volumes: ""

# Add volumes mounts, e. g. for custom secrets
volumeMounts: ""
