# Default values for webmethods-mws.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## instance name for mws
sagHome: /opt/softwareag
instanceName: default
volumeBaseMount: /opt/softwareag/MWS/volumes

replicaCount: 1

# additionals labels
labels: {}

nameOverride: ""
fullnameOverride: ""

sysadminPasswordSecret: {}
  # name:
  # key:

process: {}
  # javaMemMin: 1g
  # javaMemMax: 1g
  # javaOpts: "-server -Dtest=1 -Dtes2=2 -Dtest3=3"

externaldb: {}
  # type: postgresql
  # url: jdbc:wm:postgresql://postgres:5432;DatabaseName=webmisdb
  # user: webmisdb
  # passwordSecret:
  #   name:
  #   key:

# this is for the emptyDir provisionned for the local data folder at ${volumeBaseMount}/data
localDataDirSize: 256Mi

persistence:
  enabled: false
  # storageClassName: ""
  storageSize: 1Gi

configMaps: {}
  # apps: configMapName
  # configs: configMapName
  # libs: configMapName
  # patches: configMapName

## ports exposed by the container
containerPorts:
  runtime: 8585

## service exposing port
service:
  type: ClusterIP
  port: 8585
  targetPort: runtime
  annotations: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsUser: 1000

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
        # - path: /
        #   pathType: Prefix
        #   backendServiceName: someservice
        #   backendServicePort: 5555
  # tls:
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}