# Default values for webmethods-sample-apis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: ghcr.io/sag-gov-integration-unit
  repository: webmethods-sample-apis-bookstore
  pullPolicy: IfNotPresent
  tag: dev-0.0.4

## image pull secrets
imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 7071

# app env vars
env: []

# app specifics
appPort: 7071
appContextPath: ""
appHealthCheckPath: ""
appHealthCheckHeaders: []           

livenessProbe:
  successThreshold: 1
  failureThreshold: 3
  periodSeconds: 10
  timeoutSeconds: 3
  initialDelaySeconds: 30

## sidecar microgateway specifics
microgateway:
  enabled: false
  image:
    registry: ghcr.io/sag-gov-integration-unit
    repository: webmethods-microgateway
    pullPolicy: IfNotPresent
    tag: 10.11-latest
  commandArgs: []
  archivesConfigMap: ""
  port: 9090
  portSSL: 9091
  logLevel: WARN
  customEndpointAccess:
    enabled: true
    protocol: http
    host: ""
    port: ""
  # the licensing needed for the microgateway
  licenseSecret: {}
    # name: ""
    # key: ""
    # path: ""
  configs: {}
  env: []
  resources: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
    - ALL
  allowPrivilegeEscalation: false

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
        # - path: /
        #   pathType: Prefix
        #   backendServiceName: someservice
        #   backendServicePort: 5555
  # tls:
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
