---
{{- if .Values.transferproxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webmethods-mft-gateway.fullname" . }}-sidecareproxy
  labels:
    {{- include "webmethods-mft-gateway.labels" . | nindent 4 }}
data:
{{ tpl ((.Files.Glob "configs/haproxy.cfg").AsConfig) . | indent 2 }}
{{- end }}