apigw:
  cluster:
    aware: true
    name: {{ default "APIGatewayCluster" ((.Values.clustering).name) }}
    sessTimeout: {{ default "60" ((.Values.clustering).sessionTimeout) }}
    actionOnStartupError: {{ default "shutdown" ((.Values.clustering).actionOnStartupError) }}
    ignite:
      discoveryPort: {{ default "47100" (((.Values.clustering).ignite).discoveryPort) }}
      communicationPort: {{ default "47500" (((.Values.clustering).ignite).communicationPort) }}
      portRange: {{ default "0" (((.Values.clustering).ignite).portRange) }}
      k8sServiceName: {{ include "webmethods-apigateway.gwruntimeFullname" . }}
      k8sNamespace: {{ .Release.Namespace }}