sources:
  {{- if .Values.fullConfigs }}
  - type: YAML
    allowEdit: false
    properties:
      location: full.yml
  {{- else }}
  {{- if .Values.commonConfigs }}
  - type: YAML
    allowEdit: false
    properties:
      location: common.yml
  {{- end }}
  {{- if .Values.externalElastic.enabled }}
  - type: YAML
    allowEdit: false
    properties:
      location: elasticsearch.yml
  {{- end }}
  {{- if .Values.externalKibana.enabled }}
  - type: YAML
    allowEdit: false
    properties:
      location: kibana.yml
  {{- end }}
  {{- if include "webmethods-apigateway.isClusteringIgnite" (default "none" ((.Values.clustering).type)) }}
  - type: YAML
    allowEdit: false
    properties:
      location: clustering_ignite.yml
  {{- else }}
  {{- if include "webmethods-apigateway.isClusteringTerracotta" (default "none" ((.Values.clustering).type)) }}
  - type: YAML
    allowEdit: false
    properties:
      location: clustering_terracotta.yml
  {{- end }}
  {{- end }}
  {{- end }}