apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webmethods-api-control-plane.name-assetcatalog" . }}
  labels:
    {{- include "webmethods-api-control-plane.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.applications.assetcatalog.replicas }}
  selector:
    matchLabels:
      {{- include "webmethods-api-control-plane.selectorLabels" . | nindent 6 }}
      app: {{ .Values.applications.assetcatalog.name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.applications.assetcatalog.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "webmethods-api-control-plane.selectorLabels" . | nindent 8 }}
        app: {{ .Values.applications.assetcatalog.name }}
        date: "{{ now | unixEpoch }}"
    spec:
      serviceAccountName: {{ include "webmethods-api-control-plane.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.applications.assetcatalog.podSecurityContext | nindent 8 }}
      automountServiceAccountToken: false
      containers:
      - name: {{ .Values.applications.assetcatalog.name }}
        image: {{ .Values.applications.assetcatalog.imageName }}:{{ .Values.applications.assetcatalog.imageTag }}
        envFrom:
        - configMapRef:
            name: {{ include "webmethods-api-control-plane.name-assetcatalog" . }}
        imagePullPolicy: Always
        securityContext:
          {{- toYaml .Values.applications.assetcatalog.containerSecurityContext | nindent 10 }}
        resources:
          limits:
            cpu: {{ .Values.applications.assetcatalog.resources.limits.cpu }}
            memory: {{ .Values.applications.assetcatalog.resources.limits.memory }}
          requests:
            cpu: {{ .Values.applications.assetcatalog.resources.requests.cpu }}
            memory: {{ .Values.applications.assetcatalog.resources.requests.memory }}
        ports:
          - containerPort: 8080
            name: http
        readinessProbe:
          httpGet:
            path: /api/assetcatalog/health/readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/assetcatalog/health/liveness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 5
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretName }}
---