{{- if not .Values.applications.es_external.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webmethods-api-control-plane.name-elastic" . }}
  labels:
    {{- include "webmethods-api-control-plane.labels" . | nindent 4 }}
  {{- with .Values.applications.es.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "webmethods-api-control-plane.selectorLabels" . | nindent 4 }}
    app: {{ .Values.applications.es.name }}
  ports:
  - name: http
    protocol: TCP
    port: 9200
    targetPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webmethods-api-control-plane.name-elastic" . }}-headless
  labels:
    {{- include "webmethods-api-control-plane.labels" . | nindent 4 }}
  {{- with .Values.applications.es.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  selector:
    {{- include "webmethods-api-control-plane.selectorLabels" . | nindent 4 }}
    app: {{ .Values.applications.es.name }}
  ports:
  - name: transport
    port: 9300
---
{{- end }}