{{- if not .Values.applications.es_external.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "webmethods-api-control-plane.name-es" . }}
  labels:
    {{- include "webmethods-api-control-plane.labels" . | nindent 4 }}
    app: {{ .Values.applications.es.name }}
spec:
  serviceName: {{ include "webmethods-api-control-plane.name-es" . }}-headless
  podManagementPolicy: Parallel
  replicas: {{ .Values.applications.es.replicas }}
  selector:
    matchLabels:
      {{- include "webmethods-api-control-plane.selectorLabels" . | nindent 6 }}
      app: {{ .Values.applications.es.name }}
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.applications.es.name }}-data
      spec:
        accessModes:
          - ReadWriteOnce
        {{- if .Values.applications.es.storageClassName }}
        storageClassName: {{ .Values.applications.es.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.applications.es.storage }}
  template:
    metadata:
      {{- with .Values.applications.es.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "webmethods-api-control-plane.selectorLabels" . | nindent 8 }}
        app: {{ .Values.applications.es.name }}
        date: "{{ now | unixEpoch }}"
    spec:
      serviceAccountName: {{ include "webmethods-api-control-plane.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.applications.es.podSecurityContext | nindent 8 }}
      initContainers:
      - name: init-sysctl
        image: public.ecr.aws/docker/library/busybox:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          {{- toYaml .Values.applications.es.initContainerSecurityContext | nindent 10 }}
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
      volumes:
        - name: logs
          emptyDir: {}
      containers:
      - name: {{ .Values.applications.es.name }}
        resources:
          limits:
            cpu: {{ .Values.applications.es.resources.limits.cpu }}
            memory: {{ .Values.applications.es.resources.limits.memory }}
          requests:
            cpu: {{ .Values.applications.es.resources.requests.cpu }}
            memory: {{ .Values.applications.es.resources.requests.memory }}
        securityContext:
          {{- toYaml .Values.applications.es.containerSecurityContext | nindent 10 }}
        image: {{ .Values.applications.es.imageName }}:{{ .Values.applications.es.imageTag }}
        imagePullPolicy: "IfNotPresent"
        envFrom:
        - configMapRef:
            name: {{ include "webmethods-api-control-plane.name-es" . }}
        env:
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 20
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 5
          failureThreshold: 3
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        volumeMounts:
          - name: {{ .Values.applications.es.name }}-data
            mountPath: /usr/share/elasticsearch/data
          - name: logs
            mountPath: /usr/share/elasticsearch/logs
{{- end }}