apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webmethods-api-control-plane.name-ingress" . }}
  labels:
    {{- include "webmethods-api-control-plane.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.applications.ingress.replicas }}
  selector:
    matchLabels:
      {{- include "webmethods-api-control-plane.selectorLabels" . | nindent 6 }}
      app: {{ .Values.applications.ingress.name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.applications.ingress.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "webmethods-api-control-plane.selectorLabels" . | nindent 8 }}
        app: {{ .Values.applications.ingress.name }}
        date: "{{ now | unixEpoch }}"
    spec:
      serviceAccountName: {{ include "webmethods-api-control-plane.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.applications.ingress.podSecurityContext | nindent 8 }}
      automountServiceAccountToken: false
      containers:
      - image: {{ .Values.applications.ingress.imageName }}:{{ .Values.applications.ingress.imageTag }}
        name: {{ .Values.applications.ingress.name }}
        envFrom:
        - configMapRef:
            name: {{ include "webmethods-api-control-plane.name-ingress" . }}
        env:
        {{- if .Values.applications.es_external.enabled }}
        {{- with .Values.applications.es_external.connection.auth }}
        - name: SERVICE_ELASTICSEARCH_USERNAME
          value: {{ .userName }}
        - name: SERVICE_ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .passwordSecret.name }}
              key: {{ .passwordSecret.key }}
        {{- end }}
        {{- end }}
        imagePullPolicy: Always
        securityContext:
          {{- toYaml .Values.applications.ingress.containerSecurityContext | nindent 10 }}
        resources:
          limits:
            cpu: {{ .Values.applications.ingress.resources.limits.cpu }}
            memory: {{ .Values.applications.ingress.resources.limits.memory }}
          requests:
            cpu: {{ .Values.applications.ingress.resources.requests.cpu }}
            memory: {{ .Values.applications.ingress.resources.requests.memory }}
        ports:
          - containerPort: 8080
            name: http
        readinessProbe:
          httpGet:
            path: /api/ingress/health/readiness
            {{ if eq .Values.applications.ingress.sslEnabled true }}
            port: 8443
            scheme: HTTPS
            {{ else }}
            port: 8080
            scheme: HTTP
            {{ end }}
          initialDelaySeconds: 100
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/ingress/health/liveness
            {{ if eq .Values.applications.ingress.sslEnabled true }}
            port: 8443
            scheme: HTTPS
            {{ else }}
            port: 8080
            scheme: HTTP
            {{ end }}
          initialDelaySeconds: 100
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 5
        volumeMounts:
          {{- with .Values.applications.es_external }}
          {{- if and .enabled .connection.auth.certsSecret.name }}
          - name: es-certs
            mountPath: /mnt/certs
            readOnly: true
          {{- end }}
          {{- end }}
#  should be enabled if the certificate from host system is being mounted
#        volumeMounts:
#          - name: hostpath-volume
#            mountPath: /opt/softwareag/certs/softwareag_not_for_production.jks
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretName }}
      volumes:
        {{- with .Values.applications.es_external }}
        {{- if and .enabled .connection.auth.certsSecret.name }}
        - name: es-certs
          secret:
            secretName: {{ .connection.auth.certsSecret.name }}
        {{- end }}
        {{- end }}
#      should be enabled if the certificate from host system is being mounted
#      volumes:
#        - name: hostpath-volume
#          hostPath:
#            path: /mnt/path/in/your/host/softwareag_test.jks
#            type: File