apiVersion: v1
kind: Service
metadata:
  name: {{ include "webmethods-api-control-plane.name-ingress" . }}
  labels:
    {{- include "webmethods-api-control-plane.labels" . | nindent 4 }}
  {{- with .Values.applications.ingress.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      {{ if eq .Values.applications.ingress.sslEnabled true }}
      targetPort: 8443
      {{ else }}
      targetPort: 8080
      {{ end }}
  selector:
    {{- include "webmethods-api-control-plane.selectorLabels" . | nindent 4 }}
    app: {{ .Values.applications.ingress.name }}
  type: ClusterIP