{{- if .Values.applications.jaegertracing.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webmethods-api-control-plane.name-jaegertracing" . }}
  labels:
    {{- include "webmethods-api-control-plane.labels" . | nindent 4 }}
data:
  COLLECTOR_ZIPKIN_HOST_PORT: "9411"
  COLLECTOR_OTLP_ENABLED: "true"
---
{{- end }}