{{- if .Values.applications.jaegertracing.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webmethods-api-control-plane.name-jaegertracing" . }}-ui
  labels:
    {{- include "webmethods-api-control-plane.labels" . | nindent 4 }}
  {{- with .Values.applications.jaegertracing.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: {{ .Values.applications.jaegertracing.uiPort }}
      protocol: TCP
      targetPort: {{ .Values.applications.jaegertracing.uiPort }}
      name: http-ui
      nodePort: {{ .Values.applications.jaegertracing.extPort }}
  selector:
    {{- include "webmethods-api-control-plane.selectorLabels" . | nindent 4 }}
    app: {{ .Values.applications.jaegertracing.name }}
  type: NodePort
{{- end }}