{{- if .Values.applications.jaegertracing.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webmethods-api-control-plane.name-jaegertracing" . }}
  labels:
    {{- include "webmethods-api-control-plane.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.applications.jaegertracing.replicaCount }}
  selector:
    matchLabels:
      {{- include "webmethods-api-control-plane.selectorLabels" . | nindent 6 }}
      app: {{ .Values.applications.jaegertracing.name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.applications.jaegertracing.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "webmethods-api-control-plane.selectorLabels" . | nindent 8 }}
        app: {{ .Values.applications.jaegertracing.name }}
        date: "{{ now | unixEpoch }}"
    spec:
      serviceAccountName: {{ include "webmethods-api-control-plane.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.applications.jaegertracing.podSecurityContext | nindent 8 }}
      automountServiceAccountToken: false
      containers:
      - image: {{ .Values.applications.jaegertracing.imageName }}:{{ .Values.applications.jaegertracing.imageTag }}
        name: {{ .Values.applications.jaegertracing.name }}
        envFrom:
        - configMapRef:
            name: {{ include "webmethods-api-control-plane.name-jaegertracing" . }}
        imagePullPolicy: Always
        securityContext:
          {{- toYaml .Values.applications.jaegertracing.containerSecurityContext | nindent 10 }}
        resources:
          limits:
            cpu: {{ .Values.applications.jaegertracing.resources.limits.cpu }}
            memory: {{ .Values.applications.jaegertracing.resources.limits.memory }}
          requests:
            cpu: {{ .Values.applications.jaegertracing.resources.requests.cpu }}
            memory: {{ .Values.applications.jaegertracing.resources.requests.memory }}
        ports:
          - name: http
            containerPort: {{ .Values.applications.jaegertracing.port }}
            protocol: TCP
          - name: http-ui
            containerPort: 16686
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http-ui
          initialDelaySeconds: 60
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: http-ui
          initialDelaySeconds: 60
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 5
      terminationGracePeriodSeconds: 30
---
{{- end }} 