apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webmethods-api-control-plane.name-ui" . }}
  labels:
    {{- include "webmethods-api-control-plane.labels" . | nindent 4 }}
data:
  APICP_ENGINE_ENDPOINT: "http://{{ include "webmethods-api-control-plane.name-engine" . }}:8080"
  APICP_ASSET_CATALOG_ENDPOINT: "http://{{ include "webmethods-api-control-plane.name-assetcatalog" . }}:8080"
  OTEL_JAVAAGENT_ENABLED: "{{ .Values.applications.jaegertracing.enabled }}"
  {{- if .Values.applications.jaegertracing.enabled }}
  LOGGING_LEVEL_COM_SOFTWAREAG_CONTROLPLANE: "{{ .Values.applications.ui.logLevel }}"
  OTEL_METRICS_EXPORTER: "none"
  JAVA_OPTS: "-Dotel.exporter.otlp.endpoint=http://{{ include "webmethods-api-control-plane.name-jaegertracing" . }}:{{ .Values.applications.jaegertracing.port }} -Dotel.resource.attributes=service.name={{ .Values.applications.ui.name }}"
  {{- end }}
  {{- if .Values.applications.gainsight.enabled }}
  APICP_UI_TENANT_CLOUD_PROVIDER: "{{ .Values.applications.gainsight.tenant.cloudProvider }}"
  APICP_UI_TENANT_REGION_NAME: "{{ .Values.applications.gainsight.tenant.region }}"
  APICP_UI_TENANT_PLAN:  "{{ .Values.applications.gainsight.tenant.plan }}"
  APICP_UI_TENANT_CUSTOMER_NAME: "{{ .Values.applications.gainsight.tenant.name }}"
  APICP_UI_TENANT_COMPANY_NAME: "{{ .Values.applications.gainsight.tenant.name }}"
  APICP_UI_TENANT_STAGE_NAME: "{{ .Values.applications.gainsight.tenant.stage }}"
  APICP_UI_TENANT_GAINSIGHT_KEY: "{{ .Values.applications.gainsight.tenant.key }}"
  {{- end }}
---