---
{{- if .Values.persistence.sharedStore.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "webmethods-mft-server.fullname" . }}-sharedstore
  labels:
    {{- include "webmethods-mft-server.labels" . | nindent 4 }}
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: {{ .Values.persistence.sharedStore.storageSize }}
  {{- if .Values.persistence.sharedStore.storageClassName }}
  storageClassName: {{ .Values.persistence.sharedStore.storageClassName }}
  {{- end }}
{{- end }}