apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "webmethods-microservicesruntime.labels" . | nindent 4 }}
  name: {{ include "webmethods-microservicesruntime.fullname" . }}
data:
  {{- with .Values.configs }}
  {{- if eq .fileAccessControl.enabled true }}
  fileAccessControl.cnf: |-
    allowedWritePaths={{ .fileAccessControl.allowedWritePaths | default "" }};
    allowedReadPaths={{ .fileAccessControl.allowedReadPaths | default "" }};
    allowedDeletePaths={{ .fileAccessControl.allowedDeletePaths | default "" }};
  {{- end }}
  {{- if eq .metering.enabled true }}
  metering.agent.properties: |-
    metering.server.url={{ .metering.serverUrl | default "" }}
    metering.accumulation.period={{ .metering.accumulationPeriod | default "10" }}
    metering.report.period={{ .metering.reportPeriod | default "30" }}
  {{- end }}
  {{- end }}