{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webmethods-microservicesruntime.fullname" . }}
  labels:
    {{- include "webmethods-microservicesruntime.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "webmethods-microservicesruntime.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "webmethods-microservicesruntime.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "webmethods-microservicesruntime.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.containerPorts }}
          ports:
            - containerPort: {{ int .runtime }}
              name: runtime
              protocol: TCP
            - containerPort: {{ int .diag }}
              name: diag
              protocol: TCP
          startupProbe:
            httpGet:
              path: /invoke/wm.server/ping
              port: {{ int .runtime }}
            failureThreshold: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /invoke/wm.server/ping
              port: {{ int .runtime }}
            periodSeconds: 10
            failureThreshold: 4
            successThreshold: 1
            timeoutSeconds: 5
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          volumeMounts:
            - name: wm-derbydb-volume
              mountPath: /opt/softwareag/IntegrationServer/db
              subPath: wmderbydb
            {{- if eq .Values.persistence.logs.enabled true }}
            - name: msr-logs
              mountPath: /opt/softwareag/IntegrationServer/logs
            {{- end }}
            {{- if eq .Values.persistence.metering.enabled true }}
            - name: msr-metering
              mountPath: /opt/softwareag/common/metering/storage
            {{- end }}
            {{- if eq .Values.persistence.customdata.enabled true }}
            - name: msr-customdata
              mountPath: {{ .Values.persistence.customdata.mountPath | default "/data" }}
            {{- end }}
            {{- if .Values.msrLicenseSecret }}
            - name: msr-license
              mountPath: /opt/softwareag/IntegrationServer/config/licenseKey.xml
              subPath: licenseKey.xml
              readOnly: false
            {{- end }}
            {{- if .Values.terracottaLicenseSecret }}
            - name: terracotta-license
              mountPath: /opt/softwareag/common/conf/terracotta-license.key
              subPath: terracotta-license.key
              readOnly: false
            {{- end }} 
            {{- if eq .Values.configs.fileAccessControl.enabled true }}
            - name: msr-configs
              mountPath: /opt/softwareag/IntegrationServer/packages/WmPublic/config/fileAccessControl.cnf
              subPath: fileAccessControl.cnf
              readOnly: true
            {{- end }}
            {{- if eq .Values.configs.metering.enabled true }}
            - name: msr-configs
              mountPath: /opt/softwareag/common/metering/conf/metering.agent.properties
              subPath: metering.agent.properties
              readOnly: true
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- tpl . $ | nindent 12 }}
            {{- end }}
      volumes:
        - name: wm-derbydb-volume
          emptyDir:
            sizeLimit: {{ .Values.derbyDBSize | default "1Gi" }}
        - name: msr-configs
          configMap:
            name: {{ include "webmethods-microservicesruntime.fullname" . }}
        {{- if eq .Values.persistence.logs.enabled true }}
        - name: msr-logs
          persistentVolumeClaim:
            claimName: {{ include "webmethods-microservicesruntime.fullname" . }}-logs
        {{- end }}
        {{- if eq .Values.persistence.metering.enabled true }}
        - name: msr-metering
          persistentVolumeClaim:
            claimName: {{ include "webmethods-microservicesruntime.fullname" . }}-metering
        {{- end }}
        {{- if eq .Values.persistence.customdata.enabled true }}
        - name: msr-customdata
          persistentVolumeClaim:
            claimName: {{ include "webmethods-microservicesruntime.fullname" . }}-customdata
        {{- end }}
        {{- if .Values.msrLicenseSecret }}
        - name: msr-license
          secret:
            secretName: {{ .Values.msrLicenseSecret }}
            items:
            - key: msr-license
              path: licenseKey.xml
        {{- end }}
        {{- if .Values.terracottaLicenseSecret }}
        - name: terracotta-license
          secret:
            secretName: {{ .Values.terracottaLicenseSecret }}
            items:
            - key: terracotta-license
              path: terracotta-license.key
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- tpl . $ | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}