{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webmethods-microservicesruntime.fullname" . }}
  labels:
    {{- include "webmethods-microservicesruntime.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: runtimeport
      port: {{ .Values.service.port }}
  selector:
    {{- include "webmethods-microservicesruntime.selectorLabels" . | nindent 4 }}
{{- end }}